"""
This type stub file was generated by pyright.
"""

from .constants import *
from .display import *
from typing import Any

def assertEquals(actual: Any, expected: Any): # -> None:
	'''Passes only if the actual value exactly matches the expected one.
	'''
	...

class _AssertRaisesContext:
	'''	
		A context manager used to implement assertRaises* methods.		
	'''
	def __init__(self, expected_exception: type[Exception]) -> None:
		...
	
	def __enter__(self): # -> Self@_AssertRaisesContext:
		...
	
	def __exit__(self, exc_type: type | None, exc_value: Any, tb: Any) -> bool:
		...
	


def assertRaises(expected_exception: type[Exception]): # -> _AssertRaisesContext:
	'''
	Test fails unless an exception of class expected_exception is raised. If a different type of exception is raised, it will not be caught, and the test will exit with an error, just like it would for an unexpected exception.

	Used like this:
	.. code-block:: python
		with assertRaises(SomeException):
   			do_something()	
	'''
	...

