"""
This type stub file was generated by pyright.
"""

from .constants import *
from typing import Any, Type

def get_colour(state: TestResult): # -> str:
	...

def clearColour(): # -> None:
	...

def display_normal_message(state: TestResult, actual: Any, expected: Any): # -> None:
	...

def display_exception_message(state: TestResult, actual_exception: Type[Exception] | None, expected_exception: Type[Exception]): # -> None:
	...

