"""
This type stub file was generated by pyright.
"""

from .asserts import *

class testCase:
	__name__ = ...


def test_all(*args: type[testCase]) -> None:
	'''
	Run all the tests within the specified test case.

	If more than one test case is specified, test all the tests in each test cases
	.. code-block:: python
		bentests.test_all(ArithmeticTests, ExponentialTests)
	'''
	...

